---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: dec4633ecc15f55cbfc4fc76a2796ebf1a0c8516
      fabric8.io/git-branch: master
      prometheus.io/scrape: "true"
      prometheus.io/port: "9779"
    labels:
      expose: "true"
      provider: fabric8
      project: trains
      version: 1.0-SNAPSHOT
      group: paytm
    name: trains
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: trains
      provider: fabric8
      group: paytm
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: dec4633ecc15f55cbfc4fc76a2796ebf1a0c8516
      fabric8.io/git-branch: master
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=trains&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: trains
      version: 1.0-SNAPSHOT
      group: paytm
    name: trains
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: trains
        provider: fabric8
        group: paytm
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: dec4633ecc15f55cbfc4fc76a2796ebf1a0c8516
          fabric8.io/git-branch: master
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=trains&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: trains
          version: 1.0-SNAPSHOT
          group: paytm
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: paytm/trains:snapshot-191013-034334-0032
          imagePullPolicy: IfNotPresent
          name: funktor
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
          securityContext:
            privileged: false
